# Generated by Django 5.0.1 on 2024-02-21 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre de la localidad')),
                ('cp', models.IntegerField(max_length=10, verbose_name='Codigo postal')),
                ('provincia', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre de la localidad')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido de la localidad')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_nac', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('tipo_iva', models.CharField(choices=[('CF', 'Consumidor Final'), ('EX', 'Exento'), ('RI', 'Responsable Inscripto'), ('MT', 'Monotributo')], default='CF', max_length=2, verbose_name='Tipo de IVA')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entidad.localidad')),
            ],
        ),
    ]
