# Generated by Django 5.0.1 on 2024-03-04 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la consulta')),
                ('costo', models.PositiveIntegerField(verbose_name='Costo de la consulta')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidad.animal')),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad.enfermedad')),
            ],
        ),
    ]
