# Generated by Django 5.0.1 on 2024-02-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='cp',
            field=models.CharField(max_length=10, verbose_name='Codigo postal'),
        ),
    ]
