# Generated by Django 5.0.1 on 2024-02-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0002_alter_localidad_cp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre del instructor')),
                ('email', models.EmailField(max_length=60, verbose_name='Email del instructor')),
                ('cursos_asignados', models.IntegerField(verbose_name='Cursos asignados')),
            ],
        ),
    ]
