# Generated by Django 5.0.1 on 2024-02-22 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0003_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre del animal')),
                ('raza', models.CharField(choices=[('GD', 'Golden'), ('LD', 'Labrador'), ('RD', 'Ragdoll'), ('SD', 'Saint Bernard'), ('TD', 'Tibetan'), ('WD', 'Wild'), ('OT', 'Otro')], default='OT', max_length=2, verbose_name='Raza del animal')),
                ('categoria', models.CharField(choices=[('CN', 'Canino'), ('FO', 'Felino'), ('OT', 'Otro')], default='OT', max_length=2, verbose_name='Categoria del animal')),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidad.persona')),
            ],
        ),
    ]
